version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=smis
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=^obg3ea%a5+6i%-=0b_@4!bffq05albcsqmgxc$$572%v$$!eh&_
      - DEBUG=true
      - ALLOWED_HOSTS=localhost
      - POSTGRES_DB=smis
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    links:
      - db
    depends_on:
      - db
